{
    "name": "Anducuden A",
    "planets": [
        {
            "name": "Uncodneddrox",
            "mass": 50000,
            "position_x": 6800.0029296875,
            "position_y": -39000.01171875,
            "velocity_x": 110.71282196044922,
            "velocity_y": 19.303781509399414,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1539598976,
                "radius": 1200,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Fullnox",
            "mass": 35000,
            "position_x": 10100,
            "position_y": -50600,
            "velocity_x": -27.769065856933594,
            "velocity_y": -20.091936111450195,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 844133248,
                "radius": 550,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 10,
                "metalClusters": 10,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Qudix",
            "mass": 10000,
            "position_x": 12200,
            "position_y": -54100,
            "velocity_x": 149.78506469726562,
            "velocity_y": 86.44056701660156,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 317028992,
                "radius": 400,
                "heightRange": 35,
                "waterHeight": 49,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 34,
                "metalClusters": 34,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 2,
                "landingZoneSize": 60
            }
        },
        {
            "name": "Sadix",
            "mass": 10000,
            "position_x": 14200,
            "position_y": -55700,
            "velocity_x": 99.68515014648438,
            "velocity_y": 82.37125396728516,
            "required_thrust_to_move": 0,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 243602784,
                "radius": 400,
                "heightRange": 35,
                "waterHeight": 39,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 29,
                "metalClusters": 29,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 2,
                "landingZoneSize": 81
            }
        }
    ]
}