{
    "name": "Kereta-57B",
    "planets": [
        {
            "name": "O-01",
            "mass": 5000,
            "position_x": 0.02408035658299923,
            "position_y": 60000,
            "velocity_x": -91.28709411621094,
            "velocity_y": 0.00003264681072323583,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": false,
            "min_spawn_delay": 600,
            "max_spawn_delay": 840,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "O-02",
            "mass": 5000,
            "position_x": -0.000715492817107588,
            "position_y": -60000,
            "velocity_x": 91.28709411621094,
            "velocity_y": 0.0000029016980533924652,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 600,
            "max_spawn_delay": 840,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "O-03",
            "mass": 5000,
            "position_x": 60000,
            "position_y": -0.005245366599410772,
            "velocity_x": 0.000003990285676991334,
            "velocity_y": 91.28709411621094,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 600,
            "max_spawn_delay": 840,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Atansiri",
            "mass": 50000,
            "position_x": 12599.9990234375,
            "position_y": 2499.999755859375,
            "velocity_x": -38.39657211303711,
            "velocity_y": 193.51869201660156,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 686355968,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 26.000001907348633,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Turbulos",
            "mass": 9500,
            "position_x": 30100,
            "position_y": -8799.99609375,
            "velocity_x": -2.82318115234375,
            "velocity_y": 199.0933837890625,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 749023616,
                "radius": 450,
                "heightRange": 33,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 40,
                "metalClusters": 40,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Aunsandrio",
            "mass": 10000,
            "position_x": 33400.015625,
            "position_y": -27299.990234375,
            "velocity_x": 68.13400268554688,
            "velocity_y": 83.358154296875,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 158867200,
                "radius": 400,
                "heightRange": 35,
                "waterHeight": 38,
                "waterDepth": 100,
                "temperature": 80,
                "metalDensity": 44,
                "metalClusters": 44,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Tertantuous",
            "mass": 10000,
            "position_x": 25900,
            "position_y": -11900,
            "velocity_x": 55.296348571777344,
            "velocity_y": 120.35089111328125,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 915275328,
                "radius": 550,
                "heightRange": 35,
                "waterHeight": 34,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 38,
                "metalClusters": 38,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 2,
                "landingZoneSize": 150
            }
        },
        {
            "name": "Urtoptunsaw",
            "mass": 35000,
            "position_x": -32900,
            "position_y": 101100,
            "velocity_x": -65.21131896972656,
            "velocity_y": -21.22109603881836,
            "required_thrust_to_move": 5,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1156768128,
                "radius": 760,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 43,
                "metalClusters": 43,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}