{
    "name": "PAX Sire 2016",
    "planets": [
        {
            "name": "PAX Estrire",
            "mass": 50000,
            "position_x": 136599.984375,
            "position_y": 15900.0419921875,
            "velocity_x": -6.971465110778809,
            "velocity_y": 59.893028259277344,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 228637792,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 172,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "O-01",
            "mass": 5000,
            "position_x": -32603.529296875,
            "position_y": -44294.58203125,
            "velocity_x": 76.78768157958984,
            "velocity_y": -56.52043914794922,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": false,
            "min_spawn_delay": 1,
            "max_spawn_delay": 601,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "O-02",
            "mass": 5000,
            "position_x": 32603.515625,
            "position_y": 44294.58984375,
            "velocity_x": -76.7876968383789,
            "velocity_y": 56.52042007446289,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 1,
            "max_spawn_delay": 601,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "O-03",
            "mass": 5000,
            "position_x": -44294.58203125,
            "position_y": 32603.529296875,
            "velocity_x": -56.52043914794922,
            "velocity_y": -76.78768157958984,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 1,
            "max_spawn_delay": 601,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "O-04",
            "mass": 5000,
            "position_x": 44294.5859375,
            "position_y": -32603.5234375,
            "velocity_x": 56.52042770385742,
            "velocity_y": 76.78768920898438,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "respawn": true,
            "start_destroyed": true,
            "min_spawn_delay": 1,
            "max_spawn_delay": 601,
            "planet": {
                "seed": 8239,
                "radius": 250,
                "heightRange": 100,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 50,
                "metalDensity": 1,
                "metalClusters": 1,
                "metalSpotLimit": 5,
                "biomeScale": 100.00000013739177,
                "biome": "asteroid",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "PAX Tysipya",
            "mass": 10000,
            "position_x": 128594.953125,
            "position_y": 31198.16015625,
            "velocity_x": -55.7624626159668,
            "velocity_y": 4.268810272216797,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 84693784,
                "radius": 400,
                "heightRange": 35,
                "waterHeight": 34,
                "waterDepth": 50,
                "temperature": 80,
                "metalDensity": 51,
                "metalClusters": 51,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "terrain and CSG",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 2,
                "landingZoneSize": 165
            }
        },
        {
            "name": "PAX Shrek",
            "mass": 10000,
            "position_x": 137885.875,
            "position_y": 9383.265625,
            "velocity_x": 183.3607177734375,
            "velocity_y": 97.44939422607422,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1412917504,
                "radius": 500,
                "heightRange": 35,
                "waterHeight": 70,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 62,
                "metalClusters": 36,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "terrain and CSG",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "PAX Festri",
            "mass": 5000,
            "position_x": 92600.015625,
            "position_y": -34199.984375,
            "velocity_x": 24.657238006591797,
            "velocity_y": 66.76203918457031,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 960624128,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 82,
                "metalClusters": 50,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "PAX Meriyon",
            "mass": 35000,
            "position_x": -100,
            "position_y": -74000,
            "velocity_x": 82.19937896728516,
            "velocity_y": -0.11107664555311203,
            "required_thrust_to_move": 4,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 161237984,
                "radius": 580,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 50,
                "metalDensity": 56,
                "metalClusters": 41,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}