{
    "name": "Prodecor",
    "planets": [
        {
            "name": "Spire",
            "mass": 50000,
            "position_x": 19000.0078125,
            "position_y": 14600.001953125,
            "velocity_x": -88.01626586914062,
            "velocity_y": 114.54173278808594,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 223111760,
                "radius": 340,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 29.999998092651367,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Pris",
            "mass": 10000,
            "position_x": -53799.9921875,
            "position_y": 43400.0078125,
            "velocity_x": -53.39986801147461,
            "velocity_y": -66.19612884521484,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 1805851392,
                "radius": 340,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 59.999996185302734,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Ifdi",
            "mass": 10000,
            "position_x": -23879.98046875,
            "position_y": -38660.02734375,
            "velocity_x": 89.24432373046875,
            "velocity_y": -55.1254768371582,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 164203040,
                "radius": 340,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 70,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Quipti",
            "mass": 5000,
            "position_x": -20179.974609375,
            "position_y": -42060.01953125,
            "velocity_x": 156.73858642578125,
            "velocity_y": 18.324459075927734,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 960624128,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 45,
                "metalClusters": 45,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Chipdi",
            "mass": 5000,
            "position_x": -18300,
            "position_y": -42300,
            "velocity_x": 136.5759735107422,
            "velocity_y": 17.432682037353516,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 960624128,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 45,
                "metalClusters": 45,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Pifdi",
            "mass": 5000,
            "position_x": -21599.875,
            "position_y": -41020.0703125,
            "velocity_x": 178.01773071289062,
            "velocity_y": 30.641109466552734,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 960624128,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 45,
                "metalClusters": 45,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Fipdi",
            "mass": 5000,
            "position_x": -17579.97265625,
            "position_y": -43960.01953125,
            "velocity_x": 139.4131317138672,
            "velocity_y": 4.5093231201171875,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 960624128,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 45,
                "metalClusters": 45,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Kirs",
            "mass": 5000,
            "position_x": -51799.9921875,
            "position_y": 41400.0078125,
            "velocity_x": -147.41485595703125,
            "velocity_y": -160.21115112304688,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 960624128,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 45,
                "metalClusters": 45,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Pis",
            "mass": 5000,
            "position_x": -50599.984375,
            "position_y": 40000.00390625,
            "velocity_x": 21.956645965576172,
            "velocity_y": 4.727760314941406,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 960624128,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 45,
                "metalClusters": 45,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Dis",
            "mass": 5000,
            "position_x": -49400.07421875,
            "position_y": 38699.828125,
            "velocity_x": -117.73500061035156,
            "velocity_y": -126.42137145996094,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 960624128,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 45,
                "metalClusters": 45,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Firs",
            "mass": 5000,
            "position_x": -48400.078125,
            "position_y": 37399.828125,
            "velocity_x": -111.90005493164062,
            "velocity_y": -118.84391784667969,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 960624128,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 45,
                "metalClusters": 45,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Dire",
            "mass": 5000,
            "position_x": 21300.005859375,
            "position_y": 14300.0068359375,
            "velocity_x": -45.55450439453125,
            "velocity_y": 440.0870361328125,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 960624128,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 45,
                "metalClusters": 45,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Expire",
            "mass": 5000,
            "position_x": 22600.005859375,
            "position_y": 14200.005859375,
            "velocity_x": -59.00440216064453,
            "velocity_y": 375.6510009765625,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 960624128,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 45,
                "metalClusters": 45,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Shire",
            "mass": 5000,
            "position_x": 23900.005859375,
            "position_y": 14200.0048828125,
            "velocity_x": -69.66908264160156,
            "velocity_y": 339.29638671875,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 960624128,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 45,
                "metalClusters": 45,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Admire",
            "mass": 5000,
            "position_x": 25100.005859375,
            "position_y": 14200.017578125,
            "velocity_x": -74.78441619873047,
            "velocity_y": 316.3354187011719,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 960624128,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 45,
                "metalClusters": 45,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Wisk",
            "mass": 15000,
            "position_x": 102500,
            "position_y": -45099.9921875,
            "velocity_x": 26.911104202270508,
            "velocity_y": 61.161617279052734,
            "required_thrust_to_move": 5,
            "starting_planet": false,
            "planet": {
                "seed": 960624128,
                "radius": 350,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 40,
                "metalClusters": 40,
                "biomeScale": 50,
                "biome": "sandbox",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}