{
    "name": "Theamore II",
    "planets": [
        {
            "name": "Thorlon",
            "mass": 10000,
            "position_x": -21185.646484375,
            "position_y": -15833.486328125,
            "velocity_x": 82.31074523925781,
            "velocity_y": -110.1340560913086,
            "required_thrust_to_move": 5,
            "starting_planet": true,
            "planet": {
                "seed": 5,
                "radius": 300,
                "heightRange": 35,
                "waterHeight": 55,
                "waterDepth": 0,
                "temperature": 100,
                "metalDensity": 50,
                "metalClusters": 85,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 1,
                "landingZoneSize": 50
            }
        },
        {
            "name": "Ilasta",
            "mass": 10000,
            "position_x": -28648.60546875,
            "position_y": 28119.6875,
            "velocity_x": -78.17731475830078,
            "velocity_y": -79.6478042602539,
            "required_thrust_to_move": 5,
            "starting_planet": true,
            "planet": {
                "seed": 5,
                "radius": 300,
                "heightRange": 35,
                "waterHeight": 70,
                "waterDepth": 0,
                "temperature": 100,
                "metalDensity": 25,
                "metalClusters": 80,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Froot",
            "mass": 10000,
            "position_x": -13499.986328125,
            "position_y": -50199.9921875,
            "velocity_x": 94.70868682861328,
            "velocity_y": -25.469444274902344,
            "required_thrust_to_move": 5,
            "starting_planet": true,
            "planet": {
                "seed": 5,
                "radius": 300,
                "heightRange": 35,
                "waterHeight": 34,
                "waterDepth": 0,
                "temperature": 80,
                "metalDensity": 20,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Rogue",
            "mass": 5000,
            "position_x": -23000,
            "position_y": -15500,
            "velocity_x": 52.549049377441406,
            "velocity_y": -272.0544738769531,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 30.000001907348633,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Knob",
            "mass": 5000,
            "position_x": -24000,
            "position_y": -17800,
            "velocity_x": 13.189994812011719,
            "velocity_y": -11.212692260742188,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Rush",
            "mass": 5000,
            "position_x": -30948.65234375,
            "position_y": 28419.646484375,
            "velocity_x": -97.16397094726562,
            "velocity_y": -225.23507690429688,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 70,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Determined",
            "mass": 5000,
            "position_x": -30712.482421875,
            "position_y": 25633.5703125,
            "velocity_x": 17.53546142578125,
            "velocity_y": -159.10476684570312,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Sun",
            "mass": 5000,
            "position_x": -29788.611328125,
            "position_y": 24139.62109375,
            "velocity_x": 27.4696044921875,
            "velocity_y": -109.90811157226562,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 5,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 38,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Stench",
            "mass": 5000,
            "position_x": -30048.55859375,
            "position_y": 23219.646484375,
            "velocity_x": 17.064430236816406,
            "velocity_y": -106.85856628417969,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 3.9999990463256836,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Odd",
            "mass": 5000,
            "position_x": -18700,
            "position_y": -16800,
            "velocity_x": 131.93252563476562,
            "velocity_y": 17.481521606445312,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 54.000003814697266,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Out",
            "mass": 5000,
            "position_x": -13099.9892578125,
            "position_y": -52899.9921875,
            "velocity_x": -39.17627716064453,
            "velocity_y": -45.304115295410156,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 60.000003814697266,
                "waterDepth": 0,
                "temperature": 100,
                "metalDensity": 25,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Mon",
            "mass": 5000,
            "position_x": -12899.982421875,
            "position_y": -53899.9921875,
            "velocity_x": -19.297744750976562,
            "velocity_y": -43.957115173339844,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "In",
            "mass": 5000,
            "position_x": -12599.986328125,
            "position_y": -54699.9921875,
            "velocity_x": -7.645050048828125,
            "velocity_y": -45.940208435058594,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 6,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 70,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "M-8",
            "mass": 5000,
            "position_x": -12399.970703125,
            "position_y": -55699.99609375,
            "velocity_x": 187.29103088378906,
            "velocity_y": -6.952688217163086,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 13.000000953674316,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Arste",
            "mass": 10000,
            "position_x": 65500.0078125,
            "position_y": 700.033447265625,
            "velocity_x": 46.49971389770508,
            "velocity_y": 390.378662109375,
            "required_thrust_to_move": 7,
            "starting_planet": false,
            "planet": {
                "seed": 1087028608,
                "radius": 340,
                "heightRange": 35,
                "waterHeight": 34,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 70,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "ice_boss",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Playful",
            "mass": 50000,
            "position_x": 68100.0078125,
            "position_y": 300.0224609375,
            "velocity_x": -0.37749913334846497,
            "velocity_y": 85.68505096435547,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 583821568,
                "radius": 340,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 59.999996185302734,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}