{
    "name": "Unrutned Beta",
    "planets": [
        {
            "name": "Ufendadna",
            "mass": 5000,
            "position_x": 17800,
            "position_y": 2400,
            "velocity_x": -22.294519424438477,
            "velocity_y": 165.35096740722656,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 2139359232,
                "radius": 250,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 44,
                "metalClusters": 48,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 2,
                "landingZoneSize": 128
            }
        },
        {
            "name": "Ifendoxna",
            "mass": 5000,
            "position_x": -17899.998046875,
            "position_y": -1400.00048828125,
            "velocity_x": 13.012104034423828,
            "velocity_y": -166.36888122558594,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 1481019392,
                "radius": 250,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 0,
                "metalDensity": 45,
                "metalClusters": 45,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 2,
                "landingZoneSize": 128
            }
        },
        {
            "name": "Incodensentricity",
            "mass": 35000,
            "position_x": 13300.001953125,
            "position_y": 30999.998046875,
            "velocity_x": -111.88489532470703,
            "velocity_y": 48.002235412597656,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "respawn": false,
            "start_destroyed": false,
            "min_spawn_delay": 0,
            "max_spawn_delay": 0,
            "planet": {
                "seed": 225895280,
                "radius": 500,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 100,
                "temperature": 50,
                "metalDensity": 0,
                "metalClusters": 0,
                "metalSpotLimit": -1,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}