{
    "name": "Alpha Draconois",
    "planets": [
        {
            "name": "Pelecan",
            "mass": 50000,
            "position_x": -17000.009765625,
            "position_y": -14999.986328125,
            "velocity_x": 96.99996948242188,
            "velocity_y": -111.00010681152344,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 50,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Perfectionoid",
            "mass": 10000,
            "position_x": -5300.0009765625,
            "position_y": -18699.998046875,
            "velocity_x": 252.0780029296875,
            "velocity_y": -179.80288696289062,
            "required_thrust_to_move": 2,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 33,
                "waterDepth": 0,
                "temperature": 100,
                "metalDensity": 6,
                "metalClusters": 85,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Choiroid",
            "mass": 24000,
            "position_x": -2000.00146484375,
            "position_y": -17000,
            "velocity_x": 169.73960876464844,
            "velocity_y": -19.96937370300293,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 350,
                "heightRange": 35,
                "waterHeight": 34,
                "waterDepth": 0,
                "temperature": 50,
                "metalDensity": 11,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Monoid",
            "mass": 10000,
            "position_x": -100,
            "position_y": -18300,
            "velocity_x": 298.6614990234375,
            "velocity_y": 168.45510864257812,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 250,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 4,
                "metalClusters": 80,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Control and Dominate",
            "mass": 35000,
            "position_x": -184899.90625,
            "position_y": -66900.2890625,
            "velocity_x": -17.15679359436035,
            "velocity_y": 47.41816711425781,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 500,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 10.000000953674316,
                "metalDensity": 20,
                "metalClusters": 10,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Deridia",
            "mass": 15000,
            "position_x": 113099.9921875,
            "position_y": -78700.078125,
            "velocity_x": 34.4069938659668,
            "velocity_y": 49.446346282958984,
            "required_thrust_to_move": 4,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 350,
                "heightRange": 35,
                "waterHeight": 40,
                "waterDepth": 0,
                "temperature": 50,
                "metalDensity": 20,
                "metalClusters": 60.000003814697266,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Instuchen",
            "mass": 10000,
            "position_x": 116079.90625,
            "position_y": -79340.2578125,
            "velocity_x": 1.4588775634765625,
            "velocity_y": -103.92086791992188,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 180,
                "heightRange": 35,
                "waterHeight": 48,
                "waterDepth": 0,
                "temperature": 50,
                "metalDensity": 15.000000953674316,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}