{
    "name": "Alpha Centauri A",
    "planets": [
        {
            "name": "Cassandra",
            "mass": 50000,
            "position_x": -12200,
            "position_y": -18500,
            "velocity_x": 125.3966293334961,
            "velocity_y": -82.69398498535156,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "temperature": 57,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Ther",
            "mass": 10000,
            "position_x": -22500,
            "position_y": -27900,
            "velocity_x": 91.93864440917969,
            "velocity_y": -74.14405822753906,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 1812533632,
                "radius": 300,
                "heightRange": 20,
                "waterHeight": 33,
                "temperature": 75,
                "metalDensity": 90,
                "metalClusters": 100,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Niveus",
            "mass": 12200,
            "position_x": -56500,
            "position_y": -62499.99609375,
            "velocity_x": 57.14655685424805,
            "velocity_y": -51.660484313964844,
            "required_thrust_to_move": 5,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 365,
                "heightRange": 25,
                "waterHeight": 45,
                "temperature": 0,
                "metalDensity": 6,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Paxeus",
            "mass": 5000,
            "position_x": -56900,
            "position_y": -66499.9921875,
            "velocity_x": 179.71929931640625,
            "velocity_y": -63.917762756347656,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 1,
                "radius": 250,
                "heightRange": 10,
                "waterHeight": 70,
                "temperature": 70,
                "metalDensity": 15.000000953674316,
                "metalClusters": 90,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 3,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Entrador",
            "mass": 10000,
            "position_x": -36200.00390625,
            "position_y": -41599.99609375,
            "velocity_x": 71.83167266845703,
            "velocity_y": -62.507381439208984,
            "required_thrust_to_move": 4,
            "starting_planet": false,
            "planet": {
                "seed": 1618389632,
                "radius": 360,
                "heightRange": 10,
                "waterHeight": 50,
                "temperature": 75,
                "metalDensity": 25,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Phora",
            "mass": 6500,
            "position_x": -38700.0078125,
            "position_y": -44699.9921875,
            "velocity_x": -15.388870239257812,
            "velocity_y": 7.831962585449219,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 200,
                "heightRange": 25,
                "waterHeight": 25,
                "temperature": 75,
                "metalDensity": 10,
                "metalClusters": 65,
                "biomeScale": 75.00000006869588,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Haven",
            "mass": 5000,
            "position_x": -14599.9970703125,
            "position_y": -21000.001953125,
            "velocity_x": -68.35851287841797,
            "velocity_y": 103.310546875,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 160,
                "heightRange": 25,
                "waterHeight": 0,
                "temperature": 50,
                "metalDensity": 8,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Enquire",
            "mass": 5000,
            "position_x": -6700,
            "position_y": -17500,
            "velocity_x": 87.56695556640625,
            "velocity_y": 125.36917114257812,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 120,
                "heightRange": 20,
                "waterHeight": 0,
                "temperature": 65,
                "metalDensity": 5,
                "metalClusters": 90,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}