{
    "name": "Beta Draconois",
    "planets": [
        {
            "name": "Pelecan",
            "mass": 50000,
            "position_x": -17000.00390625,
            "position_y": -14999.99609375,
            "velocity_x": 97,
            "velocity_y": -111.00003814697266,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "temperature": 50,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Perfectionoid",
            "mass": 10000,
            "position_x": -3700.00439453125,
            "position_y": -12299.998046875,
            "velocity_x": 362.71392822265625,
            "velocity_y": -19.405628204345703,
            "required_thrust_to_move": 2,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 33,
                "temperature": 100,
                "metalDensity": 6,
                "metalClusters": 85,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Choiroid",
            "mass": 20000,
            "position_x": -3400.00390625,
            "position_y": -15099.9990234375,
            "velocity_x": 175.34268188476562,
            "velocity_y": -39.48117446899414,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 150,
                "heightRange": 35,
                "waterHeight": 34,
                "temperature": 50,
                "metalDensity": 11,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Monoid",
            "mass": 5000,
            "position_x": -4500.0078125,
            "position_y": -17100,
            "velocity_x": -8.058090209960938,
            "velocity_y": 61.38955307006836,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 0,
                "temperature": 0,
                "metalDensity": 4,
                "metalClusters": 80,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Control and Dominate",
            "mass": 35000,
            "position_x": -184899.9375,
            "position_y": -66900.2421875,
            "velocity_x": -17.15677833557129,
            "velocity_y": 47.41816711425781,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 500,
                "heightRange": 0,
                "waterHeight": 0,
                "temperature": 10.000000953674316,
                "metalDensity": 20,
                "metalClusters": 10,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Deridia",
            "mass": 15000,
            "position_x": 113099.90625,
            "position_y": -78700.1796875,
            "velocity_x": 34.407047271728516,
            "velocity_y": 49.44631576538086,
            "required_thrust_to_move": 4,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 350,
                "heightRange": 35,
                "waterHeight": 40,
                "temperature": 50,
                "metalDensity": 20,
                "metalClusters": 60.000003814697266,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Instuchen",
            "mass": 10000,
            "position_x": 115400,
            "position_y": -80700,
            "velocity_x": -68.51771545410156,
            "velocity_y": -68.9326171875,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 180,
                "heightRange": 35,
                "waterHeight": 48,
                "temperature": 50,
                "metalDensity": 15.000000953674316,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}