{
    "name": "Heck 3",
    "planets": [
        {
            "name": "X-101",
            "mass": 5000,
            "position_x": -500.0204162597656,
            "position_y": -57400,
            "velocity_x": -93.32636260986328,
            "velocity_y": 0.8129765391349792,
            "required_thrust_to_move": 1,
            "starting_planet": true,
            "planet": {
                "seed": 477421152,
                "radius": 200,
                "heightRange": 14,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 70,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "X-102",
            "mass": 5000,
            "position_x": -5900.0048828125,
            "position_y": -58600.03125,
            "velocity_x": -91.67498016357422,
            "velocity_y": 9.230072975158691,
            "required_thrust_to_move": 1,
            "starting_planet": true,
            "planet": {
                "seed": 728148352,
                "radius": 200,
                "heightRange": 14,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 70,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Dints",
            "mass": 50000,
            "position_x": 18100,
            "position_y": -800,
            "velocity_x": 7.335353374481201,
            "velocity_y": 165.96253967285156,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 815900160,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 27.000001907348633,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Y-101",
            "mass": 5000,
            "position_x": 51399.99609375,
            "position_y": -25500.009765625,
            "velocity_x": 41.48677444458008,
            "velocity_y": 83.6242904663086,
            "required_thrust_to_move": 1,
            "starting_planet": true,
            "planet": {
                "seed": 1602649472,
                "radius": 200,
                "heightRange": 14,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 70,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Y-102",
            "mass": 5000,
            "position_x": 55899.98828125,
            "position_y": -18500.001953125,
            "velocity_x": 28.95248794555664,
            "velocity_y": 87.48344421386719,
            "required_thrust_to_move": 1,
            "starting_planet": true,
            "planet": {
                "seed": 1746212736,
                "radius": 200,
                "heightRange": 14,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 70,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Monstrenuous",
            "mass": 10000,
            "position_x": 20200.015625,
            "position_y": -2099.95703125,
            "velocity_x": -160.12188720703125,
            "velocity_y": -104.55635070800781,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 592451392,
                "radius": 300,
                "heightRange": 14,
                "waterHeight": 39,
                "waterDepth": 50,
                "temperature": 80,
                "metalDensity": 20,
                "metalClusters": 70,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Beta Mexus",
            "mass": 10000,
            "position_x": 13200.03125,
            "position_y": 52899.984375,
            "velocity_x": -92.91435241699219,
            "velocity_y": 23.184736251831055,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "planet": {
                "seed": 516012896,
                "radius": 390,
                "heightRange": 10,
                "waterHeight": 33,
                "waterDepth": 50,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Alpha Mexus",
            "mass": 10000,
            "position_x": 33760.03125,
            "position_y": 42819.98828125,
            "velocity_x": 75.19750213623047,
            "velocity_y": -59.28702926635742,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "planet": {
                "seed": 425900064,
                "radius": 390,
                "heightRange": 10,
                "waterHeight": 33,
                "waterDepth": 50,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Oh",
            "mass": 5000,
            "position_x": -142700.046875,
            "position_y": 136500,
            "velocity_x": 34.78214645385742,
            "velocity_y": 36.36201858520508,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "planet": {
                "seed": 962281472,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 70,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Uh",
            "mass": 5000,
            "position_x": -132999.953125,
            "position_y": 146000.015625,
            "velocity_x": -37.19612503051758,
            "velocity_y": -33.88413619995117,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "planet": {
                "seed": 608916608,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 70,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}