{
    "name": "Nequia 3",
    "planets": [
        {
            "name": "Intequetent",
            "mass": 35000,
            "position_x": -8900.00390625,
            "position_y": -12699.9990234375,
            "velocity_x": 147,
            "velocity_y": -103.00003051757812,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 10.000000953674316,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 50,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Kenkore",
            "mass": 35000,
            "position_x": -5400.00341796875,
            "position_y": -24499.9921875,
            "velocity_x": 138,
            "velocity_y": -30.00002670288086,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 680,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 50,
                "metalDensity": 7,
                "metalClusters": 40,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "New 34R7H",
            "mass": 20000,
            "position_x": -7800.0009765625,
            "position_y": -26700,
            "velocity_x": -18.661849975585938,
            "velocity_y": 140.90301513671875,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 155,
                "heightRange": 35,
                "waterHeight": 34,
                "waterDepth": 0,
                "temperature": 50,
                "metalDensity": 4,
                "metalClusters": 40,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Ocean Bleaux",
            "mass": 5000,
            "position_x": -5600,
            "position_y": -27100,
            "velocity_x": -120.29147338867188,
            "velocity_y": -10.131860733032227,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 1315136640,
                "radius": 110,
                "heightRange": 2.000000238418579,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 4,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Intequida",
            "mass": 5000,
            "position_x": -6300,
            "position_y": -28400,
            "velocity_x": -65.74478149414062,
            "velocity_y": 17.017719268798828,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 1,
                "radius": 160,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 25,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}