{
    "name": "Orbit",
    "planets": [
        {
            "name": "Zeno",
            "mass": 50000,
            "position_x": -81899.9609375,
            "position_y": -51700.13671875,
            "velocity_x": 38.353675842285156,
            "velocity_y": -60.757354736328125,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 932968064,
                "radius": 2000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 57,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Quita",
            "mass": 43000,
            "position_x": -104599.9921875,
            "position_y": -83700,
            "velocity_x": -26.753570556640625,
            "velocity_y": -14.571643829345703,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 1059419328,
                "radius": 1500,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 29,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Water Wonder",
            "mass": 42000,
            "position_x": -116200.0078125,
            "position_y": -96899.9921875,
            "velocity_x": -109.84088897705078,
            "velocity_y": 58.44462966918945,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "planet": {
                "seed": 59122832,
                "radius": 720,
                "heightRange": 0,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 16,
                "metalDensity": 100,
                "metalClusters": 100,
                "biomeScale": 75.00000006869588,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 10,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Hell",
            "mass": 38000,
            "position_x": -122500,
            "position_y": -100699.9921875,
            "velocity_x": -22.580856323242188,
            "velocity_y": -86.22312927246094,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 630,
                "heightRange": 14,
                "waterHeight": 48,
                "waterDepth": 89,
                "temperature": 50,
                "metalDensity": 100,
                "metalClusters": 100,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 10,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Forge",
            "mass": 28000,
            "position_x": -126100,
            "position_y": -101500,
            "velocity_x": -71.82069396972656,
            "velocity_y": 135.35394287109375,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 5,
                "radius": 580,
                "heightRange": 0,
                "waterHeight": 56,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 10,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Elmindor",
            "mass": 10000,
            "position_x": -127900,
            "position_y": -101200,
            "velocity_x": -117.35639190673828,
            "velocity_y": -137.86029052734375,
            "required_thrust_to_move": 1,
            "starting_planet": false,
            "planet": {
                "seed": 1310223744,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 20.000001907348633,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 100,
                "metalClusters": 100,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}