{
    "name": "PAX Alpha 2017",
    "planets": [
        {
            "name": "PAX Alazer",
            "mass": 35000,
            "position_x": 17700.01953125,
            "position_y": -15599.9990234375,
            "velocity_x": -16.02104949951172,
            "velocity_y": -20.357017517089844,
            "required_thrust_to_move": 4,
            "starting_planet": false,
            "planet": {
                "seed": 780249920,
                "radius": 590,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 50,
                "metalDensity": 80,
                "metalClusters": 80,
                "biomeScale": 50,
                "biome": "metal",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "PAX Ammonia",
            "mass": 50000,
            "position_x": 26800.005859375,
            "position_y": -23400.001953125,
            "velocity_x": 77.96986389160156,
            "velocity_y": 89.29888153076172,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 1469112320,
                "radius": 1200,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 87,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "PAX Crater",
            "mass": 5000,
            "position_x": 17680.03515625,
            "position_y": -18239.990234375,
            "velocity_x": -273.4747009277344,
            "velocity_y": -18.408109664916992,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 275941920,
                "radius": 350,
                "heightRange": 10,
                "waterHeight": 0,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 50,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 1,
                "landingZoneSize": 0
            }
        },
        {
            "name": "PAX Ichor",
            "mass": 10000,
            "position_x": 33000,
            "position_y": -21100.001953125,
            "velocity_x": 10.343864440917969,
            "velocity_y": 271.5948486328125,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 292850656,
                "radius": 520,
                "heightRange": 35,
                "waterHeight": 33,
                "waterDepth": 50,
                "temperature": 100,
                "metalDensity": 85,
                "metalClusters": 85,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 3,
                "landingZoneSize": 120
            }
        },
        {
            "name": "PAX Leaves",
            "mass": 10000,
            "position_x": -5700.00439453125,
            "position_y": -56700,
            "velocity_x": 93.20049285888672,
            "velocity_y": -9.369364738464355,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 1774014464,
                "radius": 520,
                "heightRange": 9,
                "waterHeight": 29.000001907348633,
                "waterDepth": 50,
                "temperature": 80,
                "metalDensity": 66,
                "metalClusters": 66,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 3,
                "landingZonesPerArmy": 3,
                "landingZoneSize": 120
            }
        },
        {
            "name": "PAX Artif. P",
            "mass": 8000,
            "position_x": -3500,
            "position_y": -62000,
            "velocity_x": 179.41232299804688,
            "velocity_y": 26.41675567626953,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 1276668928,
                "radius": 370,
                "heightRange": 10,
                "waterHeight": 4.999998092651367,
                "waterDepth": 50,
                "temperature": 0,
                "metalDensity": 50,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "ice_boss",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "PAX H₂0",
            "mass": 10000,
            "position_x": -3900,
            "position_y": -12600,
            "velocity_x": -185.994384765625,
            "velocity_y": 57.569679260253906,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 1809925120,
                "radius": 380,
                "heightRange": 0,
                "waterHeight": 70,
                "waterDepth": 100,
                "temperature": 100,
                "metalDensity": 90,
                "metalClusters": 90,
                "biomeScale": 75.00000006869588,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}