{
    "name": "Prehistoric Sol",
    "planets": [
        {
            "name": "Prehistoric Earth",
            "mass": 20000,
            "position_x": -21100.001953125,
            "position_y": -9699.9931640625,
            "velocity_x": 61.289161682128906,
            "velocity_y": -133.31980895996094,
            "required_thrust_to_move": 4,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 300,
                "heightRange": 35,
                "waterHeight": 65,
                "waterDepth": 0,
                "temperature": 40,
                "metalDensity": 15.000000953674316,
                "metalClusters": 80,
                "biomeScale": 50,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Prehistoric Mercury",
            "mass": 10000,
            "position_x": -11000.0009765625,
            "position_y": -6099.9970703125,
            "velocity_x": 96.69170379638672,
            "velocity_y": -174.36216735839844,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 150,
                "heightRange": 10,
                "waterHeight": 33,
                "waterDepth": 0,
                "temperature": 90,
                "metalDensity": 5,
                "metalClusters": 95,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Prehistoric Venus",
            "mass": 10000,
            "position_x": -8399.998046875,
            "position_y": -14400.0029296875,
            "velocity_x": 149.5917510986328,
            "velocity_y": -87.26181030273438,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 3,
                "radius": 270,
                "heightRange": 20,
                "waterHeight": 35.000003814697266,
                "waterDepth": 0,
                "temperature": 100,
                "metalDensity": 15.000000953674316,
                "metalClusters": 76,
                "biomeScale": 75.00000006869588,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Prehistoric Jupiter",
            "mass": 50000,
            "position_x": 48800,
            "position_y": -6600.001953125,
            "velocity_x": 13.505017280578613,
            "velocity_y": 99.85527801513672,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 1400,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 28,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Prehistoric Saturn",
            "mass": 50000,
            "position_x": -44399.9921875,
            "position_y": -47500.0078125,
            "velocity_x": 64.06304168701172,
            "velocity_y": -59.882057189941406,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 450433440,
                "radius": 1155,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 43,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Prehistoric Uranus",
            "mass": 50000,
            "position_x": 49399.9921875,
            "position_y": -67000,
            "velocity_x": 62.37923049926758,
            "velocity_y": 45.993038177490234,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 14.999999046325684,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Prehistoric Luna",
            "mass": 5000,
            "position_x": -22500.001953125,
            "position_y": -11599.9921875,
            "velocity_x": -104.42598724365234,
            "velocity_y": -11.213882446289062,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 150,
                "heightRange": 10,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 40,
                "metalDensity": 10,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "(Prehistoric) Doom2Mars",
            "mass": 5000,
            "position_x": -20502.884765625,
            "position_y": -26936.482421875,
            "velocity_x": -16.475242614746094,
            "velocity_y": -4.282646179199219,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 757847744,
                "radius": 100,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 40,
                "metalDensity": 5,
                "metalClusters": 40,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Prehistoric Mars",
            "mass": 10000,
            "position_x": -19100.01171875,
            "position_y": -24699.9921875,
            "velocity_x": 100.10638427734375,
            "velocity_y": -77.41026306152344,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 1,
                "radius": 265,
                "heightRange": 25,
                "waterHeight": 52,
                "waterDepth": 0,
                "temperature": 25,
                "metalDensity": 50,
                "metalClusters": 50,
                "biomeScale": 75.00000006869588,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Prehistoric Neptune",
            "mass": 50000,
            "position_x": -104000,
            "position_y": -3400,
            "velocity_x": 2.264991521835327,
            "velocity_y": -69.28199768066406,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 2.0000014305114746,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Prehistoric Ganymede",
            "mass": 10000,
            "position_x": 50506.82421875,
            "position_y": -10684.9375,
            "velocity_x": -205.75732421875,
            "velocity_y": 8.240043640136719,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 210,
                "heightRange": 35,
                "waterHeight": 33,
                "waterDepth": 0,
                "temperature": 100,
                "metalDensity": 10,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Prehistoric Tritan",
            "mass": 10000,
            "position_x": -101899.984375,
            "position_y": -9900.03515625,
            "velocity_x": -179.77781677246094,
            "velocity_y": -128.095947265625,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 2,
                "radius": 180,
                "heightRange": 10,
                "waterHeight": 5.999997138977051,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 10,
                "metalClusters": 60.000003814697266,
                "biomeScale": 75.00000006869588,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Prehistoric Pluto",
            "mass": 10000,
            "position_x": 60000.01171875,
            "position_y": 106700,
            "velocity_x": -55.70693588256836,
            "velocity_y": 31.32536506652832,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 35,
                "waterHeight": 34,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 7,
                "metalClusters": 55,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Prehistoric Titan",
            "mass": 10000,
            "position_x": -44100.015625,
            "position_y": -53099.9296875,
            "velocity_x": 274.89947509765625,
            "velocity_y": -48.58796310424805,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 200,
                "heightRange": 20,
                "waterHeight": 33,
                "waterDepth": 0,
                "temperature": 100,
                "metalDensity": 15.000000953674316,
                "metalClusters": 55,
                "biomeScale": 75.00000006869588,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Prehistoric Titania",
            "mass": 5000,
            "position_x": 50500.0078125,
            "position_y": -71099.9765625,
            "velocity_x": -172.01023864746094,
            "velocity_y": -16.893207550048828,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 195,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 6,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}