{
    "name": "Sol 2",
    "planets": [
        {
            "name": "Mercury",
            "mass": 5000,
            "position_x": 10900.01171875,
            "position_y": -11499.98828125,
            "velocity_x": 128.9285888671875,
            "velocity_y": 122.20220184326172,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 200,
                "heightRange": 10,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 15.000000953674316,
                "metalClusters": 80,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Earth",
            "mass": 10000,
            "position_x": -19900.029296875,
            "position_y": -23099.9765625,
            "velocity_x": 97.02137756347656,
            "velocity_y": -83.58139038085938,
            "required_thrust_to_move": 5,
            "starting_planet": true,
            "planet": {
                "seed": 10,
                "radius": 300,
                "heightRange": 15.000001907348633,
                "waterHeight": 52,
                "waterDepth": 0,
                "temperature": 50,
                "metalDensity": 10,
                "metalClusters": 85,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Mars",
            "mass": 10000,
            "position_x": 1299.994140625,
            "position_y": -39000.00390625,
            "velocity_x": 113.13343048095703,
            "velocity_y": 3.7711024284362793,
            "required_thrust_to_move": 4,
            "starting_planet": false,
            "planet": {
                "seed": 5,
                "radius": 250,
                "heightRange": 20,
                "waterHeight": 30.000001907348633,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 50,
                "metalClusters": 50,
                "biomeScale": 75.00000006869588,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Jupiter",
            "mass": 50000,
            "position_x": 60900,
            "position_y": -6600,
            "velocity_x": 9.734184265136719,
            "velocity_y": 89.82000732421875,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 1150393472,
                "radius": 1300,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 45,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Saturn",
            "mass": 45000,
            "position_x": -92400,
            "position_y": 8200.017578125,
            "velocity_x": -6.489877223968506,
            "velocity_y": -73.12971496582031,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 1200,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 27.000001907348633,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Titan",
            "mass": 7000,
            "position_x": -87700,
            "position_y": 4300.00732421875,
            "velocity_x": 116.0774154663086,
            "velocity_y": 74.57925415039062,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 200,
                "heightRange": 10,
                "waterHeight": 46,
                "waterDepth": 0,
                "temperature": 75,
                "metalDensity": 1,
                "metalClusters": 65,
                "biomeScale": 75.00000006869588,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Ganymede",
            "mass": 7500,
            "position_x": 59799.99609375,
            "position_y": -10899.9990234375,
            "velocity_x": -220.19207763671875,
            "velocity_y": 148.63856506347656,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 210,
                "heightRange": 20,
                "waterHeight": 30.000001907348633,
                "waterDepth": 0,
                "temperature": 100,
                "metalDensity": 3,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Luna",
            "mass": 5000,
            "position_x": -20400.0078125,
            "position_y": -26499.986328125,
            "velocity_x": 216.3588104248047,
            "velocity_y": -101.13017272949219,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 165,
                "heightRange": 20,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 25,
                "metalClusters": 25,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Venus",
            "mass": 8000,
            "position_x": -20400,
            "position_y": -7800.0009765625,
            "velocity_x": 54.03696823120117,
            "velocity_y": -141.32742309570312,
            "required_thrust_to_move": 4,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 270,
                "heightRange": 20,
                "waterHeight": 33,
                "waterDepth": 0,
                "temperature": 100,
                "metalDensity": 75,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Deimos",
            "mass": 5000,
            "position_x": -999.98876953125,
            "position_y": -38600.00390625,
            "velocity_x": 137.13221740722656,
            "velocity_y": 147.7712860107422,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 10,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Phobos",
            "mass": 5000,
            "position_x": -1464.696533203125,
            "position_y": -39341.171875,
            "velocity_x": 96.72523498535156,
            "velocity_y": 136.7366180419922,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 10,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Titania",
            "mass": 5000,
            "position_x": 31700.015625,
            "position_y": 73500,
            "velocity_x": -78.65095520019531,
            "velocity_y": -156.1346435546875,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 1,
                "radius": 180,
                "heightRange": 20,
                "waterHeight": 50,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 5,
                "metalClusters": 41,
                "biomeScale": 50,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Uranus",
            "mass": 40000,
            "position_x": 25700.0078125,
            "position_y": 73600,
            "velocity_x": -75.60869598388672,
            "velocity_y": 26.401412963867188,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 1100,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 20,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Neptune",
            "mass": 41000,
            "position_x": 3999.97998046875,
            "position_y": -108500.0078125,
            "velocity_x": 67.81529998779297,
            "velocity_y": 2.500093698501587,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 934813120,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 6.000000953674316,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Pluto",
            "mass": 10000,
            "position_x": 100300.0078125,
            "position_y": -72400,
            "velocity_x": 37.21050262451172,
            "velocity_y": 51.54991912841797,
            "required_thrust_to_move": 2,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 15.000001907348633,
                "waterHeight": 34,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 0,
                "metalClusters": 10,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Triton",
            "mass": 5000,
            "position_x": 3800.0380859375,
            "position_y": -115199.9921875,
            "velocity_x": -106.98816680908203,
            "velocity_y": 7.716596603393555,
            "required_thrust_to_move": 3,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 200,
                "heightRange": 50,
                "waterHeight": 0,
                "waterDepth": 0,
                "temperature": 0,
                "metalDensity": 3,
                "metalClusters": 30.000001907348633,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}