{
    "name": "Theamore",
    "planets": [
        {
            "name": "Thorlon",
            "mass": 10000,
            "position_x": -23199.9609375,
            "position_y": -12700.078125,
            "velocity_x": 66.02169036865234,
            "velocity_y": -120.60559844970703,
            "required_thrust_to_move": 5,
            "starting_planet": true,
            "planet": {
                "seed": 5,
                "radius": 300,
                "heightRange": 35,
                "waterHeight": 55,
                "temperature": 100,
                "metalDensity": 50,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Ilasta",
            "mass": 10000,
            "position_x": -30499.9765625,
            "position_y": 26100.017578125,
            "velocity_x": -72.56230163574219,
            "velocity_y": -84.79490661621094,
            "required_thrust_to_move": 5,
            "starting_planet": true,
            "planet": {
                "seed": 5,
                "radius": 300,
                "heightRange": 35,
                "waterHeight": 70,
                "temperature": 100,
                "metalDensity": 25,
                "metalClusters": 80,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Froot",
            "mass": 10000,
            "position_x": -13500.009765625,
            "position_y": -50199.99609375,
            "velocity_x": 94.70867156982422,
            "velocity_y": -25.469480514526367,
            "required_thrust_to_move": 5,
            "starting_planet": true,
            "planet": {
                "seed": 5,
                "radius": 300,
                "heightRange": 35,
                "waterHeight": 34,
                "temperature": 80,
                "metalDensity": 20,
                "metalClusters": 75,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Montwo",
            "mass": 5000,
            "position_x": -25499.9609375,
            "position_y": -13200.078125,
            "velocity_x": 35.06013488769531,
            "velocity_y": 21.817527770996094,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 0,
                "temperature": 0,
                "metalDensity": 0,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Rogue",
            "mass": 5000,
            "position_x": -26099.962890625,
            "position_y": -14400.0751953125,
            "velocity_x": 4.344532012939453,
            "velocity_y": -15.391387939453125,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 30.000001907348633,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Knob",
            "mass": 5000,
            "position_x": -26799.9609375,
            "position_y": -15100.078125,
            "velocity_x": 6.3914031982421875,
            "velocity_y": -31.160179138183594,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 0,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Rush",
            "mass": 5000,
            "position_x": -32800.0234375,
            "position_y": 26399.974609375,
            "velocity_x": -91.54883575439453,
            "velocity_y": -230.3822021484375,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 70,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Determined",
            "mass": 5000,
            "position_x": -32563.853515625,
            "position_y": 23613.900390625,
            "velocity_x": 23.15045928955078,
            "velocity_y": -164.2518768310547,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 0,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "tropical",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Sun",
            "mass": 5000,
            "position_x": -31639.984375,
            "position_y": 22119.953125,
            "velocity_x": 33.08464050292969,
            "velocity_y": -115.05529022216797,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 5,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 38,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Stench",
            "mass": 5000,
            "position_x": -31899.9296875,
            "position_y": 21199.9765625,
            "velocity_x": 22.679428100585938,
            "velocity_y": -112.00567626953125,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 3.9999990463256836,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Odd",
            "mass": 5000,
            "position_x": -18099.9609375,
            "position_y": -14400.07421875,
            "velocity_x": 96.51885986328125,
            "velocity_y": -29.11383056640625,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 54.000003814697266,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Out",
            "mass": 5000,
            "position_x": -13100.01171875,
            "position_y": -52899.99609375,
            "velocity_x": -39.176231384277344,
            "velocity_y": -45.30419158935547,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 60.000003814697266,
                "temperature": 100,
                "metalDensity": 25,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "earth",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Mon",
            "mass": 5000,
            "position_x": -12900.0078125,
            "position_y": -53899.99609375,
            "velocity_x": -19.29779815673828,
            "velocity_y": -43.95708465576172,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 0,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "lava",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "In",
            "mass": 5000,
            "position_x": -12600.0126953125,
            "position_y": -54699.99609375,
            "velocity_x": -7.645118713378906,
            "velocity_y": -45.94017791748047,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 6,
                "radius": 100,
                "heightRange": 0,
                "waterHeight": 70,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "desert",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Dor",
            "mass": 5000,
            "position_x": -12200.013671875,
            "position_y": -55500,
            "velocity_x": 187.6732177734375,
            "velocity_y": -2.6669387817382812,
            "required_thrust_to_move": 3,
            "starting_planet": true,
            "planet": {
                "seed": 0,
                "radius": 100,
                "heightRange": 50,
                "waterHeight": 0,
                "temperature": 0,
                "metalDensity": 20,
                "metalClusters": 50,
                "biomeScale": 50,
                "biome": "moon",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        },
        {
            "name": "Gas Giant (Obviously)",
            "mass": 50000,
            "position_x": 67600,
            "position_y": 20300,
            "velocity_x": -24.206844329833984,
            "velocity_y": 80.60997009277344,
            "required_thrust_to_move": 0,
            "starting_planet": false,
            "planet": {
                "seed": 0,
                "radius": 1000,
                "heightRange": 0,
                "waterHeight": 0,
                "temperature": 13.000000953674316,
                "metalDensity": 0,
                "metalClusters": 0,
                "biomeScale": 100.00000013739177,
                "biome": "gas",
                "symmetryType": "none",
                "symmetricalMetal": false,
                "symmetricalStarts": false,
                "numArmies": 2,
                "landingZonesPerArmy": 0,
                "landingZoneSize": 0
            }
        }
    ]
}