cShareSystems.load_pas("PoseidonsTrident", [
	"coui://ui/mods/PTMP/systems/1v1.pas",
	"coui://ui/mods/PTMP/systems/1v1_..pas",
	"coui://ui/mods/PTMP/systems/alpha_centauri a.pas",
	"coui://ui/mods/PTMP/systems/alpha_draconois.pas",
	"coui://ui/mods/PTMP/systems/beta_draconois.pas",
	"coui://ui/mods/PTMP/systems/big_lava.pas",
	"coui://ui/mods/PTMP/systems/collide.pas",
	"coui://ui/mods/PTMP/systems/comm_boxing 2.pas",
	"coui://ui/mods/PTMP/systems/delta_hydri.pas",
	"coui://ui/mods/PTMP/systems/gelan,_ignus, aqua.pas",
	"coui://ui/mods/PTMP/systems/heck_3.pas",
	"coui://ui/mods/PTMP/systems/nequia_3.pas",
	
	"coui://ui/mods/PTMP/systems/orbit.pas",
	"coui://ui/mods/PTMP/systems/orbit_2.pas",
	"coui://ui/mods/PTMP/systems/pax_alpha 2016.pas",
	"coui://ui/mods/PTMP/systems/pax_alpha 2017.pas",
	"coui://ui/mods/PTMP/systems/pax_beta 2016.pas",
	"coui://ui/mods/PTMP/systems/pax_fish 2015.pas",
	"coui://ui/mods/PTMP/systems/peaceful_(not for long).pas",
	"coui://ui/mods/PTMP/systems/perpendicular_gas.pas",
	"coui://ui/mods/PTMP/systems/prehistoric_sol.pas",
	"coui://ui/mods/PTMP/systems/_1v1_final.pas",	"coui://ui/mods/PTMP/systems/prehistoric_sol_smaller.pas",
	"coui://ui/mods/PTMP/systems/sol_2.pas",
	"coui://ui/mods/PTMP/systems/_andecudden_a.pas",
	"coui://ui/mods/PTMP/systems/_big_and_less_lag_2.pas",	"coui://ui/mods/PTMP/systems/theamore.pas",
	"coui://ui/mods/PTMP/systems/unique_planets x.pas",

	"coui://ui/mods/PTMP/systems/_big_and_less_lag.pas",
	"coui://ui/mods/PTMP/systems/_destent.pas",
	"coui://ui/mods/PTMP/systems/_eest.pas",
	"coui://ui/mods/PTMP/systems/_ffa_small.pas",
	"coui://ui/mods/PTMP/systems/_gas_battles.pas",
	"coui://ui/mods/PTMP/systems/_gegeran.pas",
	"coui://ui/mods/PTMP/systems/_gels.pas",	"coui://ui/mods/PTMP/systems/_kerata-57b.pas",
	"coui://ui/mods/PTMP/systems/_lel.pas",
	"coui://ui/mods/PTMP/systems/_matol.pas",	             "coui://ui/mods/PTMP/systems/_meh.pas",	"coui://ui/mods/PTMP/systems/_pax_earth 2016.pas",	"coui://ui/mods/PTMP/systems/_pax_sire 2016.pas",	"coui://ui/mods/PTMP/systems/_prodecor.pas",	"coui://ui/mods/PTMP/systems/_rip_pa multiplayer 2019.pas",	"coui://ui/mods/PTMP/systems/_theamore_ii.pas",	"coui://ui/mods/PTMP/systems/_unrutned_beta.pas",]);